### ISSUE TITLE
When calling setState after getInitialState, if the property doesn't already exist in state then error is returned

### ISSUE THREAD

**Issue by sambomartin** [yonatanmn/reflux-state-mixin#1]
The error is `Uncaught TypeError: Cannot read property 'trigger' of undefined`

It's happening here:

``` javascript
setState: function (state) {
          var changed = false;
          var prevState = update({}, {$merge: this.state});

          for (var key in state) {
            if (state.hasOwnProperty(key)) {
              if (this.state[key] !== state[key]) {
                this[key].trigger(state[key]);
                changed = true;
              }
            }
          }
```

this is because  the state doesn't contain one of the new keys.

this is a simplified version of my store:

``` javascript
var RecordStore = Reflux.createStore({
    mixins: [StateMixin],
    listenables: [FormActions, RecordActions],  
    init: function () {
        //this.fetchList();
    },  
    getInitialState: function () {        
        return { SomeBool: false };
    },
    register : function(key,val) {
            var s = {}; s[key] = val;
            this.setState(s);   
    }
});

module.exports = RecordStore;
```

Is there a way of extending the store's initial state?

Thanks

**Comment by yonatanmn** [comment]
Currently you must declare all of the states in `getInitialState`. I thought at start that it's good practice to declare everything, because some components might listen to the entire store, and then if store state properties are dynamic it can unitentionaly override the component ones.  
I'm not sure yet about it. 
Any way, for now, you can set state of dynamic keys inside an object declared in initialState, use react's immutability helpers to update it. 
(tell me if guidance needed)
